sudo: required
services:
    - docker

# We are only running the react client app test. so this is this 
# the only before install and script to execute the test
before_install: 
    - docker build -t edgould/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true edgould/react-test npm test

# Here we build production versions of all the servers and push them off
# to Docker hub. No need to state file name for it uses Dockerfile by default
# Note the first part of the name is the docker id
after_success:
    - docker build -t euphoman/multi-client  ./client
    - docker build -t euphoman/multi-nginx ./nginx
    - docker build -t euphoman/multi-server ./server
    - docker build -t euphoman/multi-worker ./worker

    # Login into docker CLI. We will use enviroment variables created in the settings for this travis-ci project
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin 

    # Now push the production files to docker hub
    # make sure that you use correct user name that is on docker!
    - docker push euphoman/multi-client
    - docker push euphoman/multi-nginx
    - docker push euphoman/multi-server
    - docker push euphoman/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-968707750742
    bucket_path: docker-multi

    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    

